// Module and privilege keys seeded for the KUBEE_POS application in ezauth (V2__seed_data.sql).

export const PosModules = {
  DASHBOARD: 'KUBEE_POS_DASHBOARD',
  ORDERS: 'KUBEE_POS_ORDERS',
  BILLS: 'KUBEE_POS_BILLS',
  CATALOG: 'KUBEE_POS_CATALOG',
  REPORTS: 'KUBEE_POS_REPORTS',
  USER_MGMT: 'KUBEE_POS_USER_MGMT',
  SETTINGS: 'KUBEE_POS_SETTINGS',
} as const;

export const PosPrivileges = {
  DASHBOARD_VIEW: 'KUBEE_POS_DASHBOARD_VIEW',

  ORDERS_VIEW: 'KUBEE_POS_ORDERS_VIEW',
  ORDERS_CREATE: 'KUBEE_POS_ORDERS_CREATE',
  ORDERS_EDIT: 'KUBEE_POS_ORDERS_EDIT',
  ORDERS_CANCEL: 'KUBEE_POS_ORDERS_CANCEL',

  BILLS_VIEW: 'KUBEE_POS_BILLS_VIEW',
  BILLS_CREATE: 'KUBEE_POS_BILLS_CREATE',
  BILLS_DISCOUNT: 'KUBEE_POS_BILLS_DISCOUNT',
  BILLS_REFUND: 'KUBEE_POS_BILLS_REFUND',
  BILLS_VOID: 'KUBEE_POS_BILLS_VOID',
  BILLS_PRINT: 'KUBEE_POS_BILLS_PRINT',

  CATALOG_VIEW: 'KUBEE_POS_CATALOG_VIEW',
  CATALOG_CREATE: 'KUBEE_POS_CATALOG_CREATE',
  CATALOG_EDIT: 'KUBEE_POS_CATALOG_EDIT',
  CATALOG_DELETE: 'KUBEE_POS_CATALOG_DELETE',
  CATALOG_PRICING: 'KUBEE_POS_CATALOG_PRICING',

  REPORTS_VIEW: 'KUBEE_POS_REPORTS_VIEW',
  REPORTS_EXPORT: 'KUBEE_POS_REPORTS_EXPORT',

  USER_MGMT_VIEW: 'KUBEE_POS_USER_MGMT_VIEW',
  USER_MGMT_EDIT: 'KUBEE_POS_USER_MGMT_EDIT',

  SETTINGS_VIEW: 'KUBEE_POS_SETTINGS_VIEW',
  SETTINGS_EDIT: 'KUBEE_POS_SETTINGS_EDIT',
} as const;
